ignoreGeneratedHeader = false
severity = "warning"
confidence = 0.7
errorCode = 1
warningCode = 0

[rule.blank-imports]
[rule.context-as-argument]
[rule.context-keys-type]
[rule.constant-logical-expr]
[rule.datarace]
[rule.defer]
[rule.dot-imports]
[rule.early-return]
[rule.enforce-repeated-arg-type-style]
arguments = ["short"]
[rule.error-return]
[rule.error-strings]
[rule.error-naming]
[rule.exported]
[rule.increment-decrement]
[rule.var-naming]
[rule.var-declaration]
[rule.range]
[rule.receiver-naming]
[rule.time-date]
[rule.time-naming]
[rule.unexported-return]
[rule.indent-error-flow]
[rule.errorf]
[rule.empty-block]
[rule.superfluous-else]
[rule.unused-parameter]
[rule.unreachable-code]
[rule.unnecessary-format]
[rule.redefines-builtin-id]
[rule.use-any]
[rule.use-errors-new]
[rule.cyclomatic]
threshold = 10
