name: Golang CI
on:
  push:
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - 'revive.toml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref_type == 'branch' && github.ref_name != github.event.repository.default_branch }}

jobs:
  revive:
    name: Revive lint
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v5

    - name: Revive Action
      uses: morphy2k/revive-action@bd8016177e3722fe0aad85e22507805641be5bb1

  govulncheck:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
    - name: Check out repository
      uses: actions/checkout@v5

    - id: govulncheck
      uses: golang/govulncheck-action@v1
      with:
        output-format: 'sarif'
        output-file: 'govulncheck.sarif'

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: govulncheck.sarif
        category: 'govulncheck'
